import React, { useState } from 'react';
import { Modal, Pressable, FlatList, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { usePlayer } from '../context/PlayerContext';
import { PlaylistCard } from '../components/PlaylistCard';
import { TrackItem } from '../components/TrackItem';
import { TRACK_MAP } from '../data/tracks';

export function LibraryScreen(){
 const {playlists,createPlaylist,renamePlaylist,deletePlaylist,favoritesPlaylist}=usePlayer();
 const [selected,setSelected]=useState<string|null>(null); const [modal,setModal]=useState<'create'|'rename'|null>(null); const [name,setName]=useState('');
 const selectedPlaylist=selected==='liked'?favoritesPlaylist:playlists.find(p=>p.id===selected);
 const submit=()=>{if(!name.trim())return; if(modal==='create')createPlaylist(name.trim()); else if(modal==='rename'&&selectedPlaylist)renamePlaylist(selectedPlaylist.id,name.trim()); setName('');setModal(null)};
 return <View style={styles.root}><Text style={styles.kicker}>COLLECTION</Text><Text style={styles.heading}>Library</Text><Pressable style={styles.create} onPress={()=>{setName('');setModal('create')}}><Text style={styles.plus}>＋</Text><Text style={styles.createText}>New Playlist</Text></Pressable>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{paddingVertical:20}}>{[favoritesPlaylist,...playlists].map(p=><PlaylistCard key={p.id} playlist={p} onPress={()=>setSelected(p.id)}/>)}</ScrollView>
 {selectedPlaylist&&<View style={styles.detail}><View style={styles.detailHead}><View><Text style={styles.detailTitle}>{selectedPlaylist.name}</Text><Text style={styles.detailMeta}>{selectedPlaylist.trackIds.length} songs</Text></View>{selected!=='liked'&&<View style={{flexDirection:'row',gap:12}}><Pressable onPress={()=>{setName(selectedPlaylist.name);setModal('rename')}}><Text style={styles.action}>Rename</Text></Pressable><Pressable onPress={()=>{deletePlaylist(selectedPlaylist.id);setSelected(null)}}><Text style={styles.delete}>Delete</Text></Pressable></View>}</View><FlatList data={selectedPlaylist.trackIds.map(id=>TRACK_MAP[id]).filter(Boolean)} keyExtractor={x=>x.id} renderItem={({item})=><TrackItem track={item} compact}/></View>}
 <Modal transparent visible={modal!==null} animationType="fade" onRequestClose={()=>setModal(null)}><View style={styles.overlay}><View style={styles.dialog}><Text style={styles.dialogTitle}>{modal==='create'?'New Playlist':'Rename Playlist'}</Text><TextInput autoFocus value={name} onChangeText={setName} placeholder="Playlist name" placeholderTextColor="#66666f" style={styles.textInput}/><View style={styles.dialogActions}><Pressable onPress={()=>setModal(null)}><Text style={styles.cancel}>Cancel</Text></Pressable><Pressable onPress={submit}><Text style={styles.save}>Save</Text></Pressable></View></View></View></Modal>
 </View>
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#09090c',paddingTop:62,paddingHorizontal:18},kicker:{color:'#74747e',fontSize:10,fontWeight:'800',letterSpacing:2},heading:{color:'#fff',fontSize:31,fontWeight:'800',marginTop:4},create:{height:50,borderRadius:16,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',justifyContent:'center',marginTop:22},plus:{fontSize:22,color:'#08080a'},createText:{color:'#08080a',fontWeight:'800',marginLeft:6},detail:{flex:1},detailHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:12},detailTitle:{color:'#fff',fontSize:22,fontWeight:'800'},detailMeta:{color:'#777780',fontSize:12,marginTop:3},action:{color:'#fff',fontSize:12},delete:{color:'#ff607f',fontSize:12},overlay:{flex:1,backgroundColor:'#0009',justifyContent:'center',padding:25},dialog:{backgroundColor:'#18181e',borderRadius:24,padding:20,borderWidth:1,borderColor:'#2a2a31'},dialogTitle:{color:'#fff',fontSize:20,fontWeight:'800'},textInput:{height:50,borderRadius:14,backgroundColor:'#0f0f14',color:'#fff',paddingHorizontal:14,marginTop:15},dialogActions:{flexDirection:'row',justifyContent:'flex-end',gap:24,marginTop:18},cancel:{color:'#9999a2',fontWeight:'700'},save:{color:'#fff',fontWeight:'800'}});
