import React, { useMemo } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { TRACKS } from '../data/tracks';
import { usePlayer } from '../context/PlayerContext';

export function StatsScreen(){
 const {playCounts,listenSeconds}=usePlayer(); const most=useMemo(()=>[...TRACKS].sort((a,b)=>(playCounts[b.id]??0)-(playCounts[a.id]??0)).slice(0,5),[playCounts]); const genres=useMemo(()=>Object.entries(TRACKS.reduce<Record<string,number>>((a,t)=>(a[t.genre]=(a[t.genre]??0)+1,a),{})).sort((a,b)=>b[1]-a[1]).slice(0,4),[]);
 return <ScrollView style={styles.root} contentContainerStyle={styles.content}><Text style={styles.kicker}>INSIGHTS</Text><Text style={styles.heading}>Your Stats</Text><View style={styles.grid}><Stat label="Listening time" value={`${Math.floor(listenSeconds/3600)}h ${Math.floor(listenSeconds%3600/60)}m`}/><Stat label="Tracks played" value={String(Object.values(playCounts).reduce((a,b)=>a+b,0))}/></View><Text style={styles.section}>Most Played Songs</Text>{most.map((t,i)=><View key={t.id} style={styles.row}><Text style={styles.rank}>0{i+1}</Text><View style={{flex:1}}><Text style={styles.song}>{t.title}</Text><Text style={styles.meta}>{t.artist}</Text></View><Text style={styles.count}>{playCounts[t.id]??0}</Text></View>)}<Text style={styles.section}>Top Genres</Text>{genres.map(([g,n])=><View key={g} style={styles.genre}><Text style={styles.song}>{g}</Text><View style={styles.track}><View style={[styles.fill,{width:`${Math.min(100,n/TRACKS.length*100*2)}%`}]}/></View><Text style={styles.count}>{n}</Text></View>)}</ScrollView>
}
function Stat({label,value}:{label:string;value:string}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.meta}>{label}</Text></View>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#09090c'},content:{paddingTop:62,paddingHorizontal:18,paddingBottom:120},kicker:{color:'#74747e',fontSize:10,fontWeight:'800',letterSpacing:2},heading:{color:'#fff',fontSize:31,fontWeight:'800',marginTop:4},grid:{flexDirection:'row',gap:12,marginTop:24},stat:{flex:1,borderRadius:20,padding:18,backgroundColor:'#15151b'},statValue:{color:'#fff',fontSize:24,fontWeight:'800'},meta:{color:'#777780',fontSize:12,marginTop:5},section:{color:'#fff',fontSize:20,fontWeight:'800',marginTop:30,marginBottom:13},row:{flexDirection:'row',alignItems:'center',paddingVertical:10},rank:{color:'#55555e',fontSize:12,width:32},song:{color:'#fff',fontSize:14,fontWeight:'700'},count:{color:'#777780',fontSize:12},genre:{flexDirection:'row',alignItems:'center',gap:10,marginVertical:8},track:{height:6,flex:1,borderRadius:6,backgroundColor:'#24242b',overflow:'hidden'},fill:{height:6,backgroundColor:'#fff',borderRadius:6}});
